<?php

namespace App\Models\Institution;

use App\Traits\Uuids;
use Illuminate\Database\Eloquent\Model;

class Building extends Model
{
    use Uuids;

    public $incrementing = false;

    public function institution()
    {
        return $this->belongsTo('App\Models\Institution\Institution');
    }

    public function buildingPurposess() {
        return $this->belongsToMany(BuildingPurpose::class, 'building_building_purpose');
    }

    public function __toString()
    {
        return $this->building_name; // TODO: Change the autogenerated stub
    }
}
